---
title: "H3: Minimum sequencing depth"
author: "Sara Wernig-Zorc"
date: "21/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE, 
                      error = FALSE)  

knitr::opts_knit$set(root.dir = 
                       "/path/to/project_folder/results/DANPOS/ChIP-H3/Pipeline_robustness/")
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width=5, fig.height=5) 

```

```{r libraries, include=FALSE}
library(LSD)
library(corrr)
library(GenomicRanges)
library(rtracklayer)
library(org.Dm.eg.db)
library(ChIPseeker)
library(dplyr)
library(ChIPpeakAnno)
library(venneuler)
library(corrplot)
```

# Mono-nucleosomes
```{r mono-nucs: input, include=FALSE}
mono_244X <- read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/pooled/nucMACC/mono-nucMACC_scores.csv",header=TRUE)

mono_122X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/sub-sampling/pooled/nucMACC/0.5/nucMACC_scores.csv",header=TRUE)

mono_61X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/sub-sampling/pooled/nucMACC/0.25/nucMACC_scores.csv",header=TRUE)

mono_30.5X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/sub-sampling/pooled/nucMACC/0.125/nucMACC_scores.csv",header=TRUE)

mono_15.25X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/sub-sampling/pooled/nucMACC/0.0625/nucMACC_scores.csv",header=TRUE)

mono_7.6X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len140-200/pooled_samples/sub-sampling/pooled/nucMACC/0.03125/nucMACC_scores.csv",header=TRUE)
```

```{r mono-nucs:Granges, include=FALSE}
mono.244X <- GRanges(mono_244X)
#mono.183X <- GRanges(mono_183X)
mono.122X <- GRanges(mono_122X)
mono.61X <- GRanges(mono_61X)
mono.30.5X <- GRanges(mono_30.5X)
mono.15.25X <- GRanges(mono_15.25X)
```

## Overlap called nucleosomes
```{r mono-nucs: overlap}
makeVennDiagram(Peaks = list(mono.244X,mono.122X), main="Mono-nucleosome minimum seq. coverage",NameOfPeaks=c("244X","122X"),
                minoverlap = 100,ignore.strand = TRUE,totalTest = 1000000,
                scaled=TRUE, euler.d=TRUE)

#makeVennDiagram(Peaks = list(mono.244X,mono.183X,mono.122X), main="Mono-nucleosome minimum seq. coverage",NameOfPeaks=c("244X","183X","122X"),minoverlap = 100,ignore.strand = TRUE,totalTest = 1000000,scaled=TRUE, euler.d=TRUE)

makeVennDiagram(Peaks = list(mono.244X,mono.61X,mono.30.5X,mono.15.25X), main="Mono-nucleosome minimum seq. coverage",NameOfPeaks=c("244X","61X","30.5X","15.25X"),
                minoverlap = 100,ignore.strand = TRUE,totalTest = 1000000,
                scaled=TRUE, euler.d=TRUE)
```

## nucMACC score correlation
### 244X (100%) vs. 183X (75%)
```{r mono-nucs: 244X vs. 183X, eval=FALSE, include=FALSE}
mono.244Xvs183X  <- findOverlaps(mono.244X,mono.183X, minoverlap = 100)
mono_244Xvs183X <- cbind(mono.244X$nucMACC[mono.244Xvs183X@from],mono.183X$nucMACC[mono.244Xvs183X@to])
heatscatter(mono_244Xvs183X[,1],mono_244Xvs183X[,2],cor=T,xlab="244X",ylab = "183X",method = "pearson", main="Mono-nucleosomes")
cor(mono_244Xvs183X[,1],mono_244Xvs183X[,2])
```            

### 244X (100%) vs. 122X (50%)
```{r mono-nucs: 244X vs. 122X}
mono.244Xvs122X  <- findOverlaps(mono.244X,mono.122X, minoverlap = 100)
mono_244Xvs122X <- cbind(mono.244X$nucMACC[mono.244Xvs122X@from],mono.122X$nucMACC[mono.244Xvs122X@to])
heatscatter(mono_244Xvs122X[,1],mono_244Xvs122X[,2],cor=T,xlab="244X",ylab = "122X",method = "pearson", main="Mono-nucleosomes")
cor(mono_244Xvs122X[,1],mono_244Xvs122X[,2])
```

### 244X (100%) vs. 61X (25%)
```{r mono-nucs: 244X vs. 61X}
mono.244Xvs61X  <- findOverlaps(mono.244X,mono.61X, minoverlap = 100)
mono_244Xvs61X <- cbind(mono.244X$nucMACC[mono.244Xvs61X@from],mono.61X$nucMACC[mono.244Xvs61X@to])
heatscatter(mono_244Xvs61X[,1],mono_244Xvs61X[,2],cor=T,xlab="244X",ylab = "61X",method = "pearson", main="Mono-nucleosomes")
cor(mono_244Xvs61X[,1],mono_244Xvs61X[,2])
```

### 244X (100%) vs. 31X (12.5%)
```{r mono-nucs: 244X vs. 30.5X}
mono.244Xvs30.5X  <- findOverlaps(mono.244X,mono.30.5X, minoverlap = 100)
mono_244Xvs30.5X <- cbind(mono.244X$nucMACC[mono.244Xvs30.5X@from],mono.30.5X$nucMACC[mono.244Xvs30.5X@to])
heatscatter(mono_244Xvs30.5X[,1],mono_244Xvs30.5X[,2],cor=T,xlab="244X",ylab = "30.5X",method = "pearson", main="Mono-nucleosomes")
cor(mono_244Xvs30.5X[,1],mono_244Xvs30.5X[,2])
```

### 244X (100%) vs. 15X (6.3%)
```{r mono-nucs: 244X vs. 15.25X}
mono.244Xvs15.25X  <- findOverlaps(mono.244X,mono.15.25X, minoverlap = 100)
mono_244Xvs15.25X <- cbind(mono.244X$nucMACC[mono.244Xvs15.25X@from],mono.15.25X$nucMACC[mono.244Xvs15.25X@to])
heatscatter(mono_244Xvs15.25X[,1],mono_244Xvs15.25X[,2],cor=T,xlab="244X",ylab = "15.25X",method = "pearson", main="Mono-nucleosomes")
cor(mono_244Xvs15.25X[,1],mono_244Xvs15.25X[,2])
```

## Correlation matrix
```{r mono-nucs corr matrix}
corr_mono <- read.table("corrMatrix_seqDepth_monoNucs.csv",header = T,row.names=1)
#pdf("SequencingDepth_corrMatrix_monoNucs.pdf")
corrplot.mixed(as.matrix(corr_mono))
#dev.off()
```

# Sub-nucleosomes
```{r sub-nucs: input, include=FALSE}
sub_244X <- read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len50-139/MNase_ChIP-H3_1.5U/pooled/nucMACC_filt5/nucMACC_scores.csv",header=TRUE)
#sub_183X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H4/len50-139/1.5U/sub-sampling/pooled/nucMACC_0.75/nucMACC_scores.csv",header=TRUE)
sub_122X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len50-139/MNase_ChIP-H3_1.5U/sub-sampling/pooled/nucMACC_0.5/nucMACC_scores.csv",header=TRUE)
sub_61X <-  read.table("/path/to/project_folder/results/DANPOS/ChIP-H3/len50-139/MNase_ChIP-H3_1.5U/sub-sampling/pooled/nucMACC_0.25/nucMACC_scores.csv",header=TRUE)
```

```{r sub-nucs: Granges, include=FALSE}
sub.244X <- GRanges(sub_244X)
#sub.183X <- GRanges(sub_183X)
sub.122X <- GRanges(sub_122X)
sub.61X <- GRanges(sub_61X)
```

## Overlap called nucleosomes
```{r sub-nucs: overlap}
makeVennDiagram(Peaks = list(sub.244X,sub.122X,sub.61X), main="sub-nucleosome minimum seq. coverage",
                NameOfPeaks=c("244X","122X","61X"),
                minoverlap = 100,ignore.strand = TRUE,totalTest = 1000000,
                scaled=TRUE, euler.d=TRUE)

#pdf("Sub-nucs_seqDepth_overlap.pdf")
#makeVennDiagram(Peaks = list(sub.244X,sub.183X,sub.122X,sub.61X), main="sub-nucleosome minimum seq. coverage",
#                NameOfPeaks=c("244X","183X","122X","61X"),minoverlap = 100,ignore.strand = TRUE,totalTest = 1000000,
#                scaled=TRUE, euler.d=TRUE)
#dev.off()
```

## nucMACC score correlation
### 244X (100%) vs. 183X (75%)
```{r sub-nucs: 244X vs. 183X, eval=FALSE, include=FALSE}
sub.244Xvs183X  <- findOverlaps(sub.244X,sub.183X, minoverlap = 100)
#pdf("Sub-nucs_seqDepth_nucMACC-corr.pdf")
sub_244Xvs183X <- cbind(sub.244X$nucMACC[sub.244Xvs183X@from],sub.183X$nucMACC[sub.244Xvs183X@to])
heatscatter(sub_244Xvs183X[,1],sub_244Xvs183X[,2],cor=T,xlab="244X",ylab = "183X",method = "pearson", main="sub-nucleosomes")
#dev.off()
cor(sub_244Xvs183X[,1],sub_244Xvs183X[,2])
```

### 244X (100%) vs. 122X (50%)
```{r sub-nucs: 244X vs. 122X}
sub.244Xvs122X  <- findOverlaps(sub.244X,sub.122X, minoverlap = 100)
#pdf("Sub-nucs_seqDepth_nucMACC-corr.pdf")
sub_244Xvs122X <- cbind(sub.244X$nucMACC[sub.244Xvs122X@from],sub.122X$nucMACC[sub.244Xvs122X@to])
heatscatter(sub_244Xvs122X[,1],sub_244Xvs122X[,2],cor=T,xlab="244X",ylab = "122X",method = "pearson", main="sub-nucleosomes")
#dev.off()
cor(sub_244Xvs122X[,1],sub_244Xvs122X[,2])
```

### 244X (100%) vs. 61X (25%)
```{r sub-nucs: 244X vs. 61X}
sub.244Xvs61X  <- findOverlaps(sub.244X,sub.61X, minoverlap = 100)
sub_244Xvs61X <- cbind(sub.244X$nucMACC[sub.244Xvs61X@from],sub.61X$nucMACC[sub.244Xvs61X@to])
heatscatter(sub_244Xvs61X[,1],sub_244Xvs61X[,2],cor=T,xlab="244X",ylab = "61X",method = "pearson", main="sub-nucleosomes")
cor(sub_244Xvs61X[,1],sub_244Xvs61X[,2])
```

## Correlation matrix
```{r sub-nucs corr matrix}
corr_sub <- read.table("corrMatrix_seqDepth_subNucs.csv",header = T,row.names=1)
#pdf("SequencingDepth_corrMatrix_subNucs.pdf")
corrplot.mixed(as.matrix(corr_sub))
#dev.off()
```

# The End